INSERT  INTO
	ev_demand
      ( 
      ID                            
      ,STAKENO                        
      ,CHARGEPORT                     
      ,AC_ID                          
      ,VH_ID                          
      ,USER_TYPE                      
      ,OD_MODEL                       
      ,VUSE_TIME                      
      ,REMAINCAPACITY                 
      ,TARGETCAPACITY                 
      ,CHARGING_DEMAND                
      ,CREATE_TIME                    
      ,ODID                           
      ,STATUS                         
      ) 
values
      (
      :evDemand.id                            
      ,:evDemand.stakeno                       
      ,:evDemand.chargeport                    
      ,:evDemand.acId                          
      ,:evDemand.vhId                          
      ,:evDemand.userType                      
      ,:evDemand.odModel                       
      ,:evDemand.vuseTime                      
      ,:evDemand.remaincapacity                
      ,:evDemand.targetcapacity                
      ,:evDemand.chargingDemand                
      ,:evDemand.createTime                    
      ,:evDemand.odid                          
      ,:evDemand.status                        
      )